### ISSUE TITLE
Exception in thread "ForkJoinPool-6-worker-1" java.lang.OutOfMemoryError: Metaspace

### ISSUE THREAD

**Issue by axeltlarsson** [axeltlarsson/listan#12]
Händer normalt när jag stängt Ctrl-D servern och sedan försöker starta upp den igen...

**Comment by AxelTLarsson** [comment]
Förmodligen fel-inställd ec, bör ha fixat sig nu men låter det stå öppet tills vidare.

**Comment by AxelTLarsson** [comment]
Execution context: use Play's and not default Scala's ofc!
